services:
  app-5000:
    build: .
    container_name: gateway0
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output

  app-5001:
    build: .
    container_name: gateway1
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output

  app-5002:
    build: .
    container_name: gateway2
    environment:
      - PORT=5002
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output

networks:
  mynetwork:
