services:
  app-5000:
    build: .
    container_name: gateway0
    environment:
      - PORT=5000
      - REPOS=repo1,repo2
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output
      - ./5000:/app/ring

  app-5001:
    build: .
    container_name: gateway1
    environment:
      - PORT=5001
      - REPOS=repo1,repo2
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output
      - ./5001:/app/ring

  app-5002:
    build: .
    container_name: gateway2
    environment:
      - PORT=5002
      - REPOS=repo1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    volumes:
      - ./output:/app/output
      - ./5002:/app/ring

networks:
  mynetwork:
